substitutions:
  _REGION: us-central1

steps:
  - name: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    entrypoint: uv
    args:
      - run
      - scripts/deploy.py
      - --project=${PROJECT_ID}
      - --region=${_REGION}
      - --bucket=${PROJECT_ID}_cloudbuild

options:
  dynamicSubstitutions: true
  automapSubstitutions: true
